apiVersion: v1
kind: Service 
metadata:
  name: todoapp_service
  metadata: todoapp
  spec:
    selector:
      app: todolist
    ports: 
    - protocol: TCP
      port: 80
      target_port: 8080
    type: ClusterIP
